### PR TITLE
Upgrade to Tailwind 3

### PR DESCRIPTION
**Pull request by brianhelba**

### CODE REVIEW

**Comment by jtomeck** [comment]
@brianhelba - I think I have gotten this to a pretty good place, although I feel like I might be missing some states/scenarios in my improvements. Let me know if there are further changes needed.

Also, can I get your recommendation on this?
```
src/styles.scss
 45:5  ✖  Unnecessary nesting selector (&)  scss/selector-no-redundant-nesting-selector
 52:5  ✖  Unnecessary nesting selector (&)  scss/selector-no-redundant-nesting-selector
```
To me this nesting selector is necessary because it's being used to select direct children of the parent. Without the parent selector, it will select all `p`'s within these parent elements. To me the `no-redundant-nesting-selector` rule is indeed a good one to enforce, but I don't feel that this css really matches this rule.

**Comment by brianhelba** [comment]
@jtomeck Is there any more work to be done to `girder_style/templates/account/snippets/menu_item.html`? I see you didn't edit that one, and it looks like it has some non-trivial styling.

**Comment by brianhelba** [comment]
@jtomeck Can `tailwind/README.md` be deleted now, or is there still any valuable information in there?

**Comment by jtomeck** [comment]
> I see you didn't edit that one, and it looks like it has some non-trivial styling.

Good call, I'll get right on it

> Can tailwind/README.md be deleted now, or is there still any valuable information in there?

I completely forgot to pair down the readme. Let me go through it.

**Pull request merged**
